version: '3'
services:

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ADMIN_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ADMIN_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - 27017:27017
    networks:
      - store_network

  mongo_seed:
    image: mongo
    container_name: mongo_seed
    links:
      - mongodb
    volumes:
      - ./mongo_seed:/mongo_seed
    command:
      /mongo_seed/import.sh
    networks:
      - store_network

  flask:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: flask
    networks:
      - store_network
    links:
      - mongodb
    depends_on:
       mongo_seed:
          condition: service_completed_successfully
    ports:
      - 5000:5000

  react:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: react
    links:
      - flask
    ports:
      - 3000:3000
    networks:
      - store_network

networks:
  store_network:
    driver: bridge